# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Params-Validate-Micro
version:      0.032
version_from: lib/Params/Validate/Micro.pm
installdirs:  site
requires:
    Params::Validate:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
